// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/segments": {
            "get": {
                "description": "Получить все сегменты из БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Получить семгенты",
                "operationId": "get-all-segments",
                "responses": {
                    "200": {
                        "description": "Все сегменты успешно получены",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.SegmentDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавить сегмент в БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Добавить сегмент",
                "operationId": "create-segment",
                "parameters": [
                    {
                        "description": "Информация о добавляемом сегменте",
                        "name": "Segment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateOrUpdateSegmentDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Сегмент успешно создан",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateSegmentResponseDto"
                        }
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        },
        "/api/v1/segments/{slug}": {
            "get": {
                "description": "Получить сегмент из БД по названию",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Получить сегмент",
                "operationId": "get-segment-by-name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название сегмента",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегмент с данным названием успешно получен",
                        "schema": {
                            "$ref": "#/definitions/dtos.SegmentDto"
                        }
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Сегмент с данным названием не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновить сегмент в БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Обновить сегмент",
                "operationId": "update-segment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название сегмента",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о добавляемом сегменте",
                        "name": "сегменте",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateOrUpdateSegmentDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегмент с данным названием успешно обновлен",
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateSegmentResponseDto"
                        }
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Сегмент с данным названием не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервреа",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удалить сегмент в БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "segments"
                ],
                "summary": "Удалить сегмент",
                "operationId": "delete-segment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название сегмента",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Сегмент с данным названием успешно удален"
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Сегмент с данным названием не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Получить всех пользователей из БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователей",
                "operationId": "get-all-users",
                "responses": {
                    "200": {
                        "description": "Все пользователи успешно получены",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.UserDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавить пользователя в БД",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Добавить пользователя",
                "operationId": "create-user",
                "parameters": [
                    {
                        "description": "Информация о добавляемом пользователе",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь успешно создан",
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateUserResponseDto"
                        }
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userId}": {
            "get": {
                "description": "Получить пользователя из БД по идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя",
                "operationId": "get-user-by-id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор пользователя",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь с данным идентификатором успешно получен",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserDto"
                        }
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Пользователь с данным идентификатором не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userId}/active": {
            "get": {
                "description": "Получить из БД активные сегменты пользователя, в которых он участвует на момент запроса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить активные сегменты пользователя",
                "operationId": "get-active-segments-of-user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор пользователя",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Активные сегменты пользователя успешно получены",
                        "schema": {
                            "$ref": "#/definitions/dtos.UsersActiveSegments"
                        }
                    },
                    "404": {
                        "description": "Пользователь с данным идентификатором не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Возникла внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userId}/changeSegmentsOfUser": {
            "post": {
                "description": "Добавить и удалить у пользователя указанные сегменты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Изменить сегменты пользователя",
                "operationId": "change-segments-of-user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор пользователя",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Информация о добавляемых и удаляемых сегментах",
                        "name": "сегментах",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ChangeUserSegmentsDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегменты пользователя успешно изменены"
                    },
                    "400": {
                        "description": "Некорректные входные данные",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "404": {
                        "description": "Пользователь с данным идентификатором не найден",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.ChangeUserSegmentsDto": {
            "description": "Информация о добавляемых и удаляемых сегментах пользователя",
            "type": "object",
            "properties": {
                "add_to_user": {
                    "description": "Сегменты, которые будут добавляться пользователю (с датами отключения)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SegmentWithDeadlineDate"
                    }
                },
                "take_from_user": {
                    "description": "Сегменты, которые будут удаляться у пользователя",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dtos.CreateOrUpdateSegmentDto": {
            "description": "Информация о сегменте при создании",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Описание сегмента",
                    "type": "string"
                },
                "slug": {
                    "description": "Название сегмента",
                    "type": "string"
                }
            }
        },
        "dtos.CreateSegmentResponseDto": {
            "description": "Информация о сегменте при создании",
            "type": "object",
            "properties": {
                "slug": {
                    "description": "Название сегмента",
                    "type": "string"
                }
            }
        },
        "dtos.CreateUserDto": {
            "description": "Информация о пользователе при создании",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Имя пользователя",
                    "type": "string"
                }
            }
        },
        "dtos.CreateUserResponseDto": {
            "description": "Информация о пользователе при создании",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                }
            }
        },
        "dtos.ErrorDto": {
            "description": "Информация об ошибке (DTO)",
            "type": "object",
            "properties": {
                "error": {
                    "description": "Ошибка",
                    "type": "string"
                }
            }
        },
        "dtos.SegmentDto": {
            "description": "Информация о сегменте",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Описание сегмента",
                    "type": "string"
                },
                "id": {
                    "description": "Идентификатор сегмента",
                    "type": "integer"
                },
                "slug": {
                    "description": "Название сегмента",
                    "type": "string"
                }
            }
        },
        "dtos.SegmentWithDeadlineDate": {
            "description": "Информация о сегментах с датой отключения пользователя от сегмента",
            "type": "object",
            "properties": {
                "deadline_date": {
                    "description": "Дата отключения пользователя от сегмента",
                    "type": "string"
                },
                "slug": {
                    "description": "Название сегмента",
                    "type": "string"
                }
            }
        },
        "dtos.UpdateSegmentResponseDto": {
            "description": "Информация о сегменте при обновлении",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Описание сегмента",
                    "type": "string"
                },
                "id": {
                    "description": "Идентификатор сегмента",
                    "type": "integer"
                },
                "slug": {
                    "description": "Название сегмента",
                    "type": "string"
                }
            }
        },
        "dtos.UserDto": {
            "description": "Информация о пользователе",
            "type": "object",
            "properties": {
                "id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                },
                "name": {
                    "description": "Имя пользователя",
                    "type": "string"
                }
            }
        },
        "dtos.UsersActiveSegments": {
            "description": "Информация об активных сегментах пользователя",
            "type": "object",
            "properties": {
                "segments": {
                    "description": "Список активных сегментов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.SegmentWithDeadlineDate"
                    }
                },
                "user_id": {
                    "description": "Идентификатор пользователя",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Dynamic User Segmentation Service",
	Description:      "Dynamic User Segmentation Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
