name: CI/CD
on: [push, pull_request]

jobs:
  build:
    name: build 
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: cd src/dynamic-user-segmentation-service && make build
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: cd src/dynamic-user-segmentation-service && make test
